name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  SAST-analysis:
    name: SAST analysis

    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:

      security-events: write

      actions: read
      contents: read

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java-kotlin

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:java-kotlin"

        
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: app-jar
        path: build/libs/wojtula-0.0.1-SNAPSHOT.jar

  dast_analysis:
    name: DAST analysis
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/download-artifact@master
        with:
          name: app-jar
          path: app-jar
      - name: Start application
        run: java -jar app-jar/wojtula-0.0.1-SNAPSHOT.jar &
      - name: Run DAST analysis
        uses: soos-io/soos-dast-github-action@v2
        with:
          client_id: jkn8nnike
          api_key: NjkxNWE5ZDYtZDMyYy00MWYwLWJiYTYtNDAyZmYyMzk5YmNl
          project_name: "shortenURL"
          scan_mode: "baseline"
          api_url: "https://api.soos.io/api/"
          target_url: "http://127.0.0.1:8080/"

  dependency-submission:
    name: Dependecy submission
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
